<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSDB.DataAccess\CSDB.DataAccess.csproj" />
    <ProjectReference Include="..\CSDB.Entity\CSDB.Entity.csproj" />
  </ItemGroup>

</Project>
